wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751991752.916089
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 71
      - 83
      3:
      - 13
      - 15
      - 23
      4: 3.9.18
      5: 0.15.8
      8:
      - 5
